version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: hrapp
      POSTGRES_USER: hruser
      POSTGRES_PASSWORD: hrpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "7000:1080"
      - "8025:1025"


volumes:
  postgres_data:
